//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class db_Event
    {
        public int eventId { get; set; }
        public string full_date { get; set; }
        public string event_name { get; set; }
        public string from_hour { get; set; }
        public string from_minutes { get; set; }
        public string to_hour { get; set; }
        public string to_minutes { get; set; }
        public string event_status { get; set; }
        public string @fixed { get; set; }
        public int ID { get; set; }
        public string event_date { get; set; }
        public string comment { get; set; }
    }
}
