//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class db_Truma
    {
        public string Truma_Type { get; set; }
        public string Title { get; set; }
        public string Body { get; set; }
        public string Total { get; set; }
        public string FullName { get; set; }
        public string TotalMoney { get; set; }
        public Nullable<int> IsActive { get; set; }
        public string ProfilePic { get; set; }
        public Nullable<int> IsAlowComment { get; set; }
        public int Id { get; set; }
    }
}
