//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class db_TrumaPerson
    {
        public Nullable<int> Type { get; set; }
        public string ExpDate { get; set; }
        public string Payment_FullName { get; set; }
        public string Total { get; set; }
        public string Phone1 { get; set; }
        public string NumberId { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public string FlatNumber { get; set; }
        public Nullable<int> Cur { get; set; }
        public Nullable<System.DateTime> PayDate { get; set; }
        public string Comment { get; set; }
        public Nullable<System.DateTime> Lesson_date { get; set; }
        public string Lesson_Name { get; set; }
        public int Id { get; set; }
        public string Donates { get; set; }
        public string Step { get; set; }
    }
}
