//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sidur1
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Body { get; set; }
        public Nullable<int> Publish { get; set; }
        public string ProfilePic { get; set; }
        public Nullable<int> isCategory { get; set; }
        public Nullable<int> Parent { get; set; }
        public Nullable<int> Views { get; set; }
    }
}
