//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tfila
    {
        public string Name { get; set; }
        public string Time { get; set; }
        public int ID { get; set; }
        public Nullable<int> Order1 { get; set; }
        public string Hour { get; set; }
        public string Min { get; set; }
    }
}
